// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASRW7pfei0-ZrZrxFvuTl5tNN1RED97xI',
    appId: '1:879781553960:web:4d9e8812f303896b5d921d',
    messagingSenderId: '879781553960',
    projectId: 'realtimesmss',
    authDomain: 'realtimesmss.firebaseapp.com',
    storageBucket: 'realtimesmss.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABumpIR1SPRGjnfbNOgPwaGqeDskoT1Ag',
    appId: '1:879781553960:android:8c4d78ad52f9a87d5d921d',
    messagingSenderId: '879781553960',
    projectId: 'realtimesmss',
    storageBucket: 'realtimesmss.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC_brJ01mR0WHfI9HAcNoql9Ggj3xx-d8',
    appId: '1:879781553960:ios:9de993d7f3c4b6665d921d',
    messagingSenderId: '879781553960',
    projectId: 'realtimesmss',
    storageBucket: 'realtimesmss.firebasestorage.app',
    iosBundleId: 'com.example.realtimesmss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC_brJ01mR0WHfI9HAcNoql9Ggj3xx-d8',
    appId: '1:879781553960:ios:9de993d7f3c4b6665d921d',
    messagingSenderId: '879781553960',
    projectId: 'realtimesmss',
    storageBucket: 'realtimesmss.firebasestorage.app',
    iosBundleId: 'com.example.realtimesmss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASRW7pfei0-ZrZrxFvuTl5tNN1RED97xI',
    appId: '1:879781553960:web:f38672d88a3d21735d921d',
    messagingSenderId: '879781553960',
    projectId: 'realtimesmss',
    authDomain: 'realtimesmss.firebaseapp.com',
    storageBucket: 'realtimesmss.firebasestorage.app',
  );
}
